Разметка страницы
htmlacademy-adaptive/2067193-cat-energy-26 pull request #3
Opened 2022-09-03 17:40 UTC by AnneSee

Module2 task1, Изм.1

2022-09-03 19:17 UTC, Zakamsky requested changes
В целом неплохо, начало на главной вообще отличное,  а потом ты кажется устала и запуталась.
Попробуй проверить свой БЭМ в этом сервисе: https://yoksel.github.io/html-tree/
(теперь, когда видно что ты поняла принципы, можно немного помочь себе автоматикой)

почти все ошибки связаны с "очепятками" в кол-ве дефисов внутри имени элемента. НЕ путай пожалуйста элементы и их модификаторы.

И добавь пожалуйста в секции заголовки, или возможно стоит задуматься - может это не секции, а просто обертки для стилизации (`div`)?

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +    </a>
Две ссылки сильно запутают пользователей ридеров и индексирующих роботов. Хотя технически это не ошибка конечно.
Поищи в чате по ссылкам я скидывал способ с одной ссылкой (но картинки все же две, ну или свг, в твоем случае.)

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +              <a class="site-list__link site-list__link--active" href="index.html">
образцовое применение БЭМ миксинов (стр. 35), БЭМа и модификаторов!
(подглядывай сюда, если запутаешься.)

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +        <p class="weights__description">Заработать авторитет среди дворовых котов и даже собак? Серия Cat Energy Pro поможет вашему коту нарастить необходимые мышцы!</p>
тут все корректно по БЭМу, но все же это два одинаковых блока, с одинаковыми стилями, только тексты в них разные. Так может не нужно изобретать лишних БЭМ сущностей а оформить их как единый блок, а разницу, если где то есть, оформить через модификаторы?

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +        <p class="weights__description">Заработать авторитет среди дворовых котов и даже собак? Серия Cat Energy Pro поможет вашему коту нарастить необходимые мышцы!</p>
И в этом месте, у меня вопрос, если завтра нам скажут что контуры заменят на реальные фото котов, или скажем на многоцветные иконки, логика этого раздела изменится?
А стрелочки, если поменяют на треугольники?
А если нет то зачем мы их тащим в разметку?

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +        <!--Декоративные картинки how -->
и тут ты полностью права, и с модификаторами отлично!

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +          <img class="weights__image slim__arrow" src="img/content/arrow-right.svg" alt="Перейти в каталог">
`.slim__arrow` - элемент соседнего блока. Понимаю что опечатка просто, но такого быть не должно.

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +                <dd class="history__item--desc">затрачено времени</dd>
а в этом месте мы с модификаторами перегибаем сразу дважды:
1. модификатор не может существовать без самого элемента, т.е. не возможен просто `class="history__item--desc"` обязательно нужно указать сам класс БЕЗ модификатора: `class="history__item history__item--desc"`
2. мы модифицируем почему-то то родительский элемент

Очень похоже на то что это просто опечатка в синтаксисе и мы имели тут ввиду отдельные элементы:
```html
<div class="history__item">
    <dt class="history__item-number">5 КГ</dt>
    <dd class="history__item-desc">снижение веса</dd>
</div>
```

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +        </address>
Тут вновь толи модификаторы без элементы, толи ошибка в синтаксисе.

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +          <svg class="foter-logo__icon" width="128" height="24" viewBox="0 0 128 24" fill="currentcolor" xmlns="http://www.w3.org/2000/svg">
`foter-logo__link`
`foter-logo__icon`
так fOOter или fOter? =)

2022-09-03 19:17 UTC, Zakamsky commented on source/index.html
> +                <path fill-rule="evenodd" clip-rule="evenodd" d="M19.4608 0.152905C19.6393 0.302216 19.7255 0.534898 19.6872 0.764481L17.0611 16.5214C17.0244 16.7411 16.8789 16.9273 16.6745 17.0159C1
на ссылках модификаторы верные, а на иконках проблема.
з.ы. ты ведь уже догадалась?

2022-09-03 19:17 UTC, Zakamsky commented on source/catalog.html
> +            <br class="product__title--br">500 г
Опять модифицируем что то не то..

2022-09-03 19:17 UTC, Zakamsky commented on source/catalog.html
> +              <dt class="product__item">Вкус</dt>
и снова модификатор вместо элемента

2022-09-03 19:17 UTC, Zakamsky commented on source/catalog.html
> +        </article>
Я бы в целом каждую карточку сделал отдельным блоком, что если ее захотят отдельно разместить на главной?  и на странице товара сделают показ похожих товаров?
тащить туда весь раздел ради сохранности БЭМа?

но это не требование конечно, просто размышление по оптимизации.

2022-09-03 19:17 UTC, Zakamsky commented on source/catalog.html
> +    <section class="main-inner_additional additional">
тут очипятка два подчеркивания должно быть в делителе

2022-09-03 19:17 UTC, Zakamsky commented on source/catalog.html
> +          </dl>
о, вот тут хорошо, каждый продукт - отдельный блок.

2022-09-03 19:17 UTC, Zakamsky commented on source/catalog.html
> +      <div class="gift_wrapper">
очипятка

2022-09-03 19:17 UTC, Zakamsky commented on source/catalog.html
> +          <br class="gift__desc--break">кота в подарок!
мод-ы вместо элементов опять...

2022-09-03 19:17 UTC, Zakamsky commented on source/form.html
> +      <h2 class="main-form__title">Подбор программы</h2>
а где `h1`?

2022-09-03 19:17 UTC, Zakamsky commented on source/form.html
> +      <h2 class="main-form__title">Подбор программы</h2>
структура документа выстраивается его заголовками и в ней не должно быть дыр или прыжков.

2022-09-03 19:17 UTC, Zakamsky commented on source/form.html
> +            <input class="search-form__text" id="search-form__age" type="text" placeholder="7">
я что то не уверен что сервер переварит если в поле возраст написать "старый" а в вес "толстый" есть подозрение что сервер ожидает тут числовые значения...

2022-09-03 19:17 UTC, Zakamsky commented on source/form.html
> +                  class="result-form__input"
![image](https://user-images.githubusercontent.com/35491086/188284871-cda9e3e1-aae8-409e-bc75-91b9bf9854f4.png)
Такого с радио происходить не должно, думаю ты сама знаешь как исправить, просто забыла.

Кстати, тут снова мод-ы вместо элементов на спанах...

2022-09-03 19:17 UTC, Zakamsky commented on source/form.html
> +            <input class="owner-form__text" id="owner-form__phone" type="text" placeholder="8 (960) 900-60-90">
Для емайла и телефона есть соответствующие типы полей, они помогают пользователю заполнить поля, а нам валидировать ввод.

2022-09-08 10:12 UTC, AnneSee commented on source/index.html
> +    </a>
Исправила, объединила

2022-09-08 10:12 UTC, AnneSee commented on source/index.html
> +        <p class="weights__description">Заработать авторитет среди дворовых котов и даже собак? Серия Cat Energy Pro поможет вашему коту нарастить необходимые мышцы!</p>
Убрала из html

2022-09-08 10:22 UTC, AnneSee commented on source/index.html
> +          <img class="weights__image slim__arrow" src="img/content/arrow-right.svg" alt="Перейти в каталог">
Перенесла изображение в папку декоративные, из кода удалила

2022-09-08 11:49 UTC, AnneSee commented on source/catalog.html
> +        </article>
`<div>
<article class="product__wrapper">
</article>
<a class="button product__button" href="#">Заказать</a>
</div>`
таким образом?

2022-09-08 11:51 UTC, AnneSee commented on source/catalog.html
> +        </article>
Я не правила пока)

2022-09-08 14:53 UTC, Zakamsky approved these changes
ты отлично все исправила, единственное крохотное замечание, для телефона мы используем поле не `type="number"` а `type="tel"` так браузер вспомнит что пользователь уже вводил номер телефона и предложит заполнить его из памяти.
В остальном все отлично!

2022-09-08 14:53 UTC, merged