3.14. Стилизация
htmlacademy-adaptive/2067193-cat-energy-26 pull request #4
Opened 2022-09-13 17:37 UTC by AnneSee

заданы фоновые цвета;
заданы параметры текста: шрифты, размеры шрифта, межстрочные расстояния, цвет текста;
внешние и внутренние отступы;

2022-09-13 19:51 UTC, Zakamsky requested changes
Вижу старательно проделанную работу, ты разобралась с принципами препроцессора, и кажется забыла подключить шрифты.

Давай их подключим и можно двигаться дальше.

upd: а на главной правда что ли нет ни одного контентного изображения?  давай подскажу - присмотрись к ведерку (это фото товара) и котам в слайдере (они продают главную услугу)

2022-09-13 19:51 UTC, Zakamsky commented on index.html
> +<body class="page__body">
А это что за файл у нас, и почему он в корне проекта?

2022-09-13 19:51 UTC, Zakamsky commented on source/sass/blocks/button.scss
> +  width: 280px;
Здорово что ты делаешь кнопку отдельнфым блоком.
А вот размерами кнопки лучше управлять через паддинги и минимальную ширину.
Попробуй задать в свои кнопки побольше текста и они тебя удивят...

2022-09-13 19:51 UTC, Zakamsky commented on source/sass/blocks/page__body.scss
> +  font-family: "Oswald", "Arial", sans-serif;
`.page__body` это элемент блока `.page` и стили элемента должны быть в файле блока. Не надо создавать каждому элементу по файлу, это раздует структуру нашего проекта.

2022-09-13 19:51 UTC, Zakamsky commented on source/sass/blocks/visually-hidden.scss
> +}
так ты убиваешь элемент в дереве доступности - если это временное решение то ок, если нет - погугли любое решение доступного скрытия (у вас есть примеры в метриалах)

2022-09-13 19:51 UTC, Zakamsky commented on source/sass/style.scss
> +@import "./blocks/page__body.scss";
Соблоюдай порядок подключения не по алфавиту, а в соответсвии с важностью стилей и каскадом.
Так у тебя стили тэга боди будут получены браузером и применены только после рассчета стилей из 23х других блоков... что может вызвать неслабую перереисвоку.

Обычно сперва подключают переменные и миксины, потом глобьальные стили:
- подключение шрифтов (кстати где оно?)
- стили для всего проекта (стили тэгов штмл, боди, глобальные тсили проекта)
- общие блоки (вищуалли-хидден, кнопки, заголовки)
- остальные блоки (тут браузер дорисует нужны епараметры кнопкам и уже не будет сперва отрисовывать и рассчитывать параметры и только потом скрывать скрытые элементы)

Кстати очень рекомендую уже сейчас применить глобально стили box-sizing: 
```scss
*, *:before, *::after {
  box-sizing: boredr-box
}
```
найди в чате поиском я сикдывал статьи и писал об этом. иначе придется слоднее высчитывать область контента и размеры контейнеров.

2022-09-14 09:14 UTC, AnneSee commented on source/sass/blocks/visually-hidden.scss
> +}
Исправлено

2022-09-14 13:55 UTC, AnneSee commented on index.html
> +<body class="page__body">
Фаил удалила, 
шрифты подключила,
контент добавила, но пока без перекрытия кота

2022-09-14 16:36 UTC, Zakamsky approved these changes
Хорошая работа над ошибками. Давай двигаться дальше!

2022-09-14 16:36 UTC, Zakamsky commented on source/sass/blocks/fonts.scss
> +}
что то мне подсказывает что это не про шрифты все же... 
может в какой то файл глобальных стилей?
или этот переименовать файл просто?

2022-09-14 16:37 UTC, merged